version: 2.1

orbs:
  android: circleci/android@0.2.1
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permission
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Depedency
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
          key: 'android-orb-v1-{{ epoch }}'
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Lint Test
          command: ./gradlew lint
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: artifact-file